---
all:
  children:
    monitoring:
      hosts:
        grafana:
          ansible_host: 192.168.99.99
          ansible_user: vagrant
          ansible_password: vagrant
    nodes:
      hosts:
        node-1:
          ansible_host: 192.168.99.98
          ansible_user: vagrant
          ansible_password: vagrant
        # node-2:
        #   ansible_host: 192.168.99.97
        #   ansible_user: vagrant
        #   ansible_password: vagrant
