---
all:
  children:
    monitoring:
      hosts:
        grafana:
          ansible_host: 192.168.99.99
          ansible_user: vagrant
          ansible_password: vagrant
        node1:
          ansible_host: 192.168.99.98
          ansible_user: vagrant
          ansible_password: vagrant
